CREATE TABLE public.tb_chat_mensagem (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id int8 NOT NULL,
    role varchar(20) NOT NULL,
    conteudo text NOT NULL,
    criado_em timestamp(6) NOT NULL DEFAULT now(),
    CONSTRAINT tb_chat_mensagem_pkey PRIMARY KEY (id),
    CONSTRAINT tb_chat_mensagem_role_check CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT fk_chat_mensagem_usuario FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

CREATE INDEX idx_chat_mensagem_usuario_criado
    ON public.tb_chat_mensagem (usuario_id, criado_em);
