CREATE TABLE public.tb_chat_auditoria (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id int8 NOT NULL,
    ferramenta varchar(80) NOT NULL,
    detalhe text,
    criado_em timestamp(6) NOT NULL DEFAULT now(),
    CONSTRAINT tb_chat_auditoria_pkey PRIMARY KEY (id),
    CONSTRAINT fk_chat_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

CREATE INDEX idx_chat_auditoria_usuario_criado
    ON public.tb_chat_auditoria (usuario_id, criado_em);
