-- ============================================================================
-- Core4 ERP — Schema baseline (consolidated from DDL.sql)
-- This is the authoritative schema definition. All tables, sequences,
-- constraints and indexes are included.
-- ============================================================================

-- Sequences -------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS public.tb_cartao_credito_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_categoria_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_conta_baixada_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_conta_corrente_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_conta_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_conta_investimento_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_fatura_cartao_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_lancamento_cartao_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_notificacao_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_parceiro_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_transacao_investimento_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.tb_usuario_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;

-- Tables (ordered by dependency) ----------------------------------------------

-- 1. tb_usuario (no FK dependencies)
CREATE TABLE IF NOT EXISTS public.tb_usuario (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    email varchar(255) NOT NULL,
    nome varchar(255) NOT NULL,
    "role" varchar(50) NOT NULL,
    senha_hash varchar(255) NOT NULL,
    telefone int8,
    foto_perfil text,
    CONSTRAINT tb_usuario_pkey PRIMARY KEY (id),
    CONSTRAINT ukspmnyb4dsul95fjmr5kmdmvub UNIQUE (email)
);

-- 2. tb_categoria (depends on tb_usuario)
CREATE TABLE IF NOT EXISTS public.tb_categoria (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    descricao varchar(255) NOT NULL,
    usuario_id int8 NOT NULL,
    icone varchar(255),
    CONSTRAINT tb_categoria_pkey PRIMARY KEY (id),
    CONSTRAINT fkivayrej1eklq4vli06pyyowvu FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

-- 3. tb_conta_corrente (depends on tb_usuario)
CREATE TABLE IF NOT EXISTS public.tb_conta_corrente (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    descricao varchar(255) NOT NULL,
    saldo numeric(15, 2) NOT NULL,
    usuario_id int8 NOT NULL,
    agencia varchar(255) NOT NULL,
    numero_conta varchar(255) NOT NULL,
    CONSTRAINT tb_conta_corrente_pkey PRIMARY KEY (id),
    CONSTRAINT uk2x4wi59tkk2ejvq55qdoqausb UNIQUE (numero_conta),
    CONSTRAINT fkdjcnk0m0h28ry6irya00f87ra FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

-- 4. tb_conta_investimento (depends on tb_usuario)
CREATE TABLE IF NOT EXISTS public.tb_conta_investimento (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    nome varchar(255) NOT NULL,
    saldo_atual numeric(15, 2) NOT NULL,
    tipo varchar(20) NOT NULL,
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_conta_investimento_pkey PRIMARY KEY (id),
    CONSTRAINT tb_conta_investimento_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['RENDA_FIXA','RENDA_VARIAVEL','FUNDOS','CRIPTO','OUTROS'])::text[]))),
    CONSTRAINT fk3a3xn66h0d944hxjl657gp488 FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

-- 5. tb_notificacao (depends on tb_usuario)
CREATE TABLE IF NOT EXISTS public.tb_notificacao (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    data_criacao timestamp(6) NOT NULL,
    lida bool NOT NULL,
    mensagem varchar(500) NOT NULL,
    referencia_id int8,
    tipo varchar(20) NOT NULL,
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_notificacao_pkey PRIMARY KEY (id),
    CONSTRAINT tb_notificacao_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['VENCIMENTO','FATURA'])::text[]))),
    CONSTRAINT fkj2s9y26as67rfbwx14csjru1x FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);
CREATE INDEX IF NOT EXISTS idx_notif_usuario_lida ON public.tb_notificacao USING btree (usuario_id, lida);
CREATE INDEX IF NOT EXISTS idx_notif_usuario_tipo_ref ON public.tb_notificacao USING btree (usuario_id, tipo, referencia_id);

-- 6. tb_parceiro (depends on tb_usuario)
CREATE TABLE IF NOT EXISTS public.tb_parceiro (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    cpf_cnpj varchar(18),
    nome_fantasia varchar(255),
    razao_social varchar(255),
    tipo varchar(20) NOT NULL,
    usuario_id int8 NOT NULL,
    bairro varchar(255),
    cep varchar(9),
    complemento varchar(255),
    email varchar(255),
    logradouro varchar(255),
    municipio varchar(255),
    numero varchar(255),
    telefone varchar(255),
    uf varchar(2),
    CONSTRAINT tb_parceiro_pkey PRIMARY KEY (id),
    CONSTRAINT tb_parceiro_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['CLIENTE','FORNECEDOR','AMBOS'])::text[]))),
    CONSTRAINT fkbbivedqgpmr163fp7jgc57wft FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

-- 7. tb_transacao_investimento (depends on tb_usuario, tb_conta_corrente, tb_conta_investimento)
CREATE TABLE IF NOT EXISTS public.tb_transacao_investimento (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    data_transacao date NOT NULL,
    tipo_transacao varchar(15) NOT NULL,
    valor numeric(15, 2) NOT NULL,
    conta_corrente_origem_id int8,
    conta_investimento_id int8 NOT NULL,
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_transacao_investimento_pkey PRIMARY KEY (id),
    CONSTRAINT tb_transacao_investimento_tipo_transacao_check CHECK (((tipo_transacao)::text = ANY ((ARRAY['APORTE','RESGATE','RENDIMENTO'])::text[]))),
    CONSTRAINT fk9h6jl42g0trxkoak1rgujiqwq FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id),
    CONSTRAINT fkmuafebbyv0ngd3n172q7f0544 FOREIGN KEY (conta_corrente_origem_id) REFERENCES public.tb_conta_corrente(id),
    CONSTRAINT fkngdmh2ui0qahmikdtff0j8d6r FOREIGN KEY (conta_investimento_id) REFERENCES public.tb_conta_investimento(id)
);

-- 8. tb_cartao_credito (depends on tb_usuario, tb_conta_corrente)
CREATE TABLE IF NOT EXISTS public.tb_cartao_credito (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    dia_fechamento int4 NOT NULL,
    dia_vencimento int4 NOT NULL,
    limite numeric(15, 2) NOT NULL,
    nome varchar(100) NOT NULL,
    conta_corrente_id int8 NOT NULL,
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_cartao_credito_pkey PRIMARY KEY (id),
    CONSTRAINT fk3x2knrcuqthnd425rbqnia5nd FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id),
    CONSTRAINT fkmiqvni1kqe7ieyg91t6l0p63k FOREIGN KEY (conta_corrente_id) REFERENCES public.tb_conta_corrente(id)
);

-- 9. tb_conta (depends on tb_usuario, tb_categoria, tb_parceiro)
CREATE TABLE IF NOT EXISTS public.tb_conta (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    data_vencimento date NOT NULL,
    descricao varchar(255) NOT NULL,
    grupo_parcelamento varchar(255),
    numero_parcela int4 NOT NULL,
    status varchar(10) NOT NULL,
    tipo varchar(10) NOT NULL,
    total_parcelas int4 NOT NULL,
    valor_original numeric(15, 2) NOT NULL,
    categoria_id int8 NOT NULL,
    parceiro_id int8,
    usuario_id int8 NOT NULL,
    acrescimo numeric(15, 2),
    desconto numeric(15, 2),
    numero_documento varchar(255),
    CONSTRAINT tb_conta_pkey PRIMARY KEY (id),
    CONSTRAINT tb_conta_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE','ATRASADO','PAGO','RECEBIDO'])::text[]))),
    CONSTRAINT tb_conta_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PAGAR','RECEBER'])::text[]))),
    CONSTRAINT fk9h7osvev2x22brakn0o3eblbw FOREIGN KEY (categoria_id) REFERENCES public.tb_categoria(id),
    CONSTRAINT fkb7x81d7mw2c4yexqrbbsn6tha FOREIGN KEY (parceiro_id) REFERENCES public.tb_parceiro(id),
    CONSTRAINT fke0eplrystos5hicf7mf9uffse FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

-- 10. tb_conta_baixada (depends on tb_conta, tb_conta_corrente, tb_usuario)
CREATE TABLE IF NOT EXISTS public.tb_conta_baixada (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    acrescimo numeric(15, 2) NOT NULL,
    data_pagamento date NOT NULL,
    desconto numeric(15, 2) NOT NULL,
    juros numeric(15, 2) NOT NULL,
    multa numeric(15, 2) NOT NULL,
    valor_final numeric(15, 2) NOT NULL,
    conta_id int8 NOT NULL,
    conta_corrente_id int8 NOT NULL,
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_conta_baixada_pkey PRIMARY KEY (id),
    CONSTRAINT ukbx95g0pxvqemx96wh7l3s3j01 UNIQUE (conta_id),
    CONSTRAINT fk187pmcu5j8fx8nt1cdrdjk6r0 FOREIGN KEY (conta_corrente_id) REFERENCES public.tb_conta_corrente(id),
    CONSTRAINT fkesyidfsslbo61d7d779u1rut7 FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id),
    CONSTRAINT fkrt5i1blvqs3jrk082qfcs6823 FOREIGN KEY (conta_id) REFERENCES public.tb_conta(id)
);

-- 11. tb_fatura_cartao (depends on tb_cartao_credito, tb_conta, tb_usuario)
CREATE TABLE IF NOT EXISTS public.tb_fatura_cartao (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    ano int4 NOT NULL,
    mes int4 NOT NULL,
    status varchar(10) NOT NULL,
    cartao_credito_id int8 NOT NULL,
    conta_id int8,
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_fatura_cartao_pkey PRIMARY KEY (id),
    CONSTRAINT tb_fatura_cartao_status_check CHECK (((status)::text = ANY ((ARRAY['ABERTA','FECHADA'])::text[]))),
    CONSTRAINT uk7ft0vfr12f87vmv1staj40kug UNIQUE (conta_id),
    CONSTRAINT uklxms7djiy12j49morkwebsl7a UNIQUE (cartao_credito_id, mes, ano, usuario_id),
    CONSTRAINT fk2r67fdqnylp77hdl3ytjbppp9 FOREIGN KEY (cartao_credito_id) REFERENCES public.tb_cartao_credito(id),
    CONSTRAINT fkdcm8up062nw210pjwkp73w7o2 FOREIGN KEY (conta_id) REFERENCES public.tb_conta(id),
    CONSTRAINT fkk8cf3nlusei2nedbgcenmb4j1 FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

-- 12. tb_lancamento_cartao (depends on tb_cartao_credito, tb_categoria, tb_usuario)
CREATE TABLE IF NOT EXISTS public.tb_lancamento_cartao (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    ano_fatura int4 NOT NULL,
    data_compra date NOT NULL,
    descricao varchar(255) NOT NULL,
    grupo_parcelamento varchar(255),
    mes_fatura int4 NOT NULL,
    numero_parcela int4 NOT NULL,
    total_parcelas int4 NOT NULL,
    valor numeric(15, 2) NOT NULL,
    cartao_credito_id int8 NOT NULL,
    categoria_id int8 NOT NULL,
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_lancamento_cartao_pkey PRIMARY KEY (id),
    CONSTRAINT fkjd2865fv9xm6t9qon1ethwbiq FOREIGN KEY (categoria_id) REFERENCES public.tb_categoria(id),
    CONSTRAINT fkp1cmuje998by066b7dk881h8l FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id),
    CONSTRAINT fkrubo2ll27jcqp698qk3ya79xb FOREIGN KEY (cartao_credito_id) REFERENCES public.tb_cartao_credito(id)
);
