CREATE TABLE public.tb_assinatura (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    descricao varchar(255) NOT NULL,
    valor numeric(15, 2) NOT NULL,
    dia_vencimento int4 NOT NULL,
    ativa bool NOT NULL DEFAULT true,
    categoria_id int8 NOT NULL,
    parceiro_id int8,
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_assinatura_pkey PRIMARY KEY (id),
    CONSTRAINT tb_assinatura_dia_check CHECK (dia_vencimento >= 1 AND dia_vencimento <= 31),
    CONSTRAINT fk_assinatura_categoria FOREIGN KEY (categoria_id) REFERENCES public.tb_categoria(id),
    CONSTRAINT fk_assinatura_parceiro FOREIGN KEY (parceiro_id) REFERENCES public.tb_parceiro(id),
    CONSTRAINT fk_assinatura_usuario FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);
