CREATE TABLE public.tb_conciliacao (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    data_conciliacao timestamp(6) NOT NULL,
    conta_corrente_id int8 NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDENTE',
    banco_id varchar(20),
    agencia varchar(20),
    numero_conta_ofx varchar(50),
    data_inicio_ofx date,
    data_fim_ofx date,
    total_transacoes int4 NOT NULL DEFAULT 0,
    total_conciliados int4 NOT NULL DEFAULT 0,
    total_nao_identificados int4 NOT NULL DEFAULT 0,
    observacao varchar(500),
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_conciliacao_pkey PRIMARY KEY (id),
    CONSTRAINT tb_conciliacao_status_check CHECK (status IN ('PENDENTE','FINALIZADA','CANCELADA')),
    CONSTRAINT fk_conciliacao_cc FOREIGN KEY (conta_corrente_id) REFERENCES public.tb_conta_corrente(id),
    CONSTRAINT fk_conciliacao_usuario FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

CREATE TABLE public.tb_conciliacao_item (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by varchar(100),
    created_date timestamp(6),
    last_modified_by varchar(100),
    last_modified_date timestamp(6),
    conciliacao_id int8 NOT NULL,
    ofx_id varchar(100) NOT NULL,
    ofx_tipo varchar(20),
    ofx_valor numeric(15,2) NOT NULL,
    ofx_data date NOT NULL,
    ofx_memo varchar(500),
    ofx_nome varchar(255),
    conta_id int8,
    score_vinculacao int4,
    status_item varchar(30) NOT NULL DEFAULT 'NAO_IDENTIFICADO',
    conta_criada_aqui boolean NOT NULL DEFAULT false,
    conta_baixada_id int8,
    usuario_id int8 NOT NULL,
    CONSTRAINT tb_conciliacao_item_pkey PRIMARY KEY (id),
    CONSTRAINT tb_conciliacao_item_status_check CHECK (
        status_item IN ('SUGERIDO','VINCULADO_MANUALMENTE','NAO_IDENTIFICADO','IGNORADO','BAIXADO')
    ),
    CONSTRAINT uq_conciliacao_item_ofx UNIQUE (conciliacao_id, ofx_id),
    CONSTRAINT fk_ci_conciliacao FOREIGN KEY (conciliacao_id) REFERENCES public.tb_conciliacao(id),
    CONSTRAINT fk_ci_conta FOREIGN KEY (conta_id) REFERENCES public.tb_conta(id),
    CONSTRAINT fk_ci_baixada FOREIGN KEY (conta_baixada_id) REFERENCES public.tb_conta_baixada(id),
    CONSTRAINT fk_ci_usuario FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);

CREATE INDEX idx_conc_usuario ON public.tb_conciliacao(usuario_id, status);
CREATE INDEX idx_conc_item_conc ON public.tb_conciliacao_item(conciliacao_id);
CREATE INDEX idx_conc_item_conta ON public.tb_conciliacao_item(conta_id);
