-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.tb_cartao_credito_id_seq;

CREATE SEQUENCE public.tb_cartao_credito_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_categoria_id_seq;

CREATE SEQUENCE public.tb_categoria_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_conta_baixada_id_seq;

CREATE SEQUENCE public.tb_conta_baixada_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_conta_corrente_id_seq;

CREATE SEQUENCE public.tb_conta_corrente_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_conta_id_seq;

CREATE SEQUENCE public.tb_conta_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_conta_investimento_id_seq;

CREATE SEQUENCE public.tb_conta_investimento_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_lancamento_cartao_id_seq;

CREATE SEQUENCE public.tb_lancamento_cartao_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_notificacao_id_seq;

CREATE SEQUENCE public.tb_notificacao_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_parceiro_id_seq;

CREATE SEQUENCE public.tb_parceiro_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_transacao_investimento_id_seq;

CREATE SEQUENCE public.tb_transacao_investimento_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_usuario_id_seq;

CREATE SEQUENCE public.tb_usuario_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.tb_usuario definição

-- Drop table

-- DROP TABLE public.tb_usuario;

CREATE TABLE public.tb_usuario (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	email varchar(255) NOT NULL,
	nome varchar(255) NOT NULL,
	"role" varchar(50) NOT NULL,
	senha_hash varchar(255) NOT NULL,
	telefone int8 NULL,
	CONSTRAINT tb_usuario_pkey PRIMARY KEY (id),
	CONSTRAINT ukspmnyb4dsul95fjmr5kmdmvub UNIQUE (email)
);


-- public.tb_categoria definição

-- Drop table

-- DROP TABLE public.tb_categoria;

CREATE TABLE public.tb_categoria (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	descricao varchar(255) NOT NULL,
	usuario_id int8 NOT NULL,
	icone varchar(255) NULL,
	CONSTRAINT tb_categoria_pkey PRIMARY KEY (id),
	CONSTRAINT fkivayrej1eklq4vli06pyyowvu FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);


-- public.tb_conta_corrente definição

-- Drop table

-- DROP TABLE public.tb_conta_corrente;

CREATE TABLE public.tb_conta_corrente (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	apelido varchar(100) NOT NULL,
	descricao varchar(255) NOT NULL,
	saldo numeric(15, 2) NOT NULL,
	usuario_id int8 NOT NULL,
	CONSTRAINT tb_conta_corrente_pkey PRIMARY KEY (id),
	CONSTRAINT fkdjcnk0m0h28ry6irya00f87ra FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);


-- public.tb_conta_investimento definição

-- Drop table

-- DROP TABLE public.tb_conta_investimento;

CREATE TABLE public.tb_conta_investimento (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	nome varchar(255) NOT NULL,
	saldo_atual numeric(15, 2) NOT NULL,
	tipo varchar(20) NOT NULL,
	usuario_id int8 NOT NULL,
	CONSTRAINT tb_conta_investimento_pkey PRIMARY KEY (id),
	CONSTRAINT tb_conta_investimento_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['RENDA_FIXA'::character varying, 'RENDA_VARIAVEL'::character varying, 'FUNDOS'::character varying, 'CRIPTO'::character varying, 'OUTROS'::character varying])::text[]))),
	CONSTRAINT fk3a3xn66h0d944hxjl657gp488 FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);


-- public.tb_notificacao definição

-- Drop table

-- DROP TABLE public.tb_notificacao;

CREATE TABLE public.tb_notificacao (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	data_criacao timestamp(6) NOT NULL,
	lida bool NOT NULL,
	mensagem varchar(500) NOT NULL,
	referencia_id int8 NULL,
	tipo varchar(20) NOT NULL,
	usuario_id int8 NOT NULL,
	CONSTRAINT tb_notificacao_pkey PRIMARY KEY (id),
	CONSTRAINT tb_notificacao_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['VENCIMENTO'::character varying, 'FATURA'::character varying])::text[]))),
	CONSTRAINT fkj2s9y26as67rfbwx14csjru1x FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);
CREATE INDEX idx_notif_usuario_lida ON public.tb_notificacao USING btree (usuario_id, lida);
CREATE INDEX idx_notif_usuario_tipo_ref ON public.tb_notificacao USING btree (usuario_id, tipo, referencia_id);


-- public.tb_parceiro definição

-- Drop table

-- DROP TABLE public.tb_parceiro;

CREATE TABLE public.tb_parceiro (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	cpf_cnpj varchar(18) NULL,
	data_nascimento_fundacao date NULL,
	endereco varchar(500) NULL,
	nome varchar(255) NOT NULL,
	nome_fantasia varchar(255) NULL,
	razao_social varchar(255) NULL,
	tipo varchar(20) NOT NULL,
	usuario_id int8 NOT NULL,
	bairro varchar(255) NULL,
	cep varchar(9) NULL,
	complemento varchar(255) NULL,
	email varchar(255) NULL,
	logradouro varchar(255) NULL,
	municipio varchar(255) NULL,
	numero varchar(255) NULL,
	telefone varchar(255) NULL,
	uf varchar(2) NULL,
	CONSTRAINT tb_parceiro_pkey PRIMARY KEY (id),
	CONSTRAINT tb_parceiro_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['CLIENTE'::character varying, 'FORNECEDOR'::character varying, 'AMBOS'::character varying])::text[]))),
	CONSTRAINT fkbbivedqgpmr163fp7jgc57wft FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);


-- public.tb_transacao_investimento definição

-- Drop table

-- DROP TABLE public.tb_transacao_investimento;

CREATE TABLE public.tb_transacao_investimento (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	data_transacao date NOT NULL,
	tipo_transacao varchar(15) NOT NULL,
	valor numeric(15, 2) NOT NULL,
	conta_corrente_origem_id int8 NULL,
	conta_investimento_id int8 NOT NULL,
	usuario_id int8 NOT NULL,
	CONSTRAINT tb_transacao_investimento_pkey PRIMARY KEY (id),
	CONSTRAINT tb_transacao_investimento_tipo_transacao_check CHECK (((tipo_transacao)::text = ANY ((ARRAY['APORTE'::character varying, 'RESGATE'::character varying, 'RENDIMENTO'::character varying])::text[]))),
	CONSTRAINT fk9h6jl42g0trxkoak1rgujiqwq FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id),
	CONSTRAINT fkmuafebbyv0ngd3n172q7f0544 FOREIGN KEY (conta_corrente_origem_id) REFERENCES public.tb_conta_corrente(id),
	CONSTRAINT fkngdmh2ui0qahmikdtff0j8d6r FOREIGN KEY (conta_investimento_id) REFERENCES public.tb_conta_investimento(id)
);


-- public.tb_cartao_credito definição

-- Drop table

-- DROP TABLE public.tb_cartao_credito;

CREATE TABLE public.tb_cartao_credito (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	dia_fechamento int4 NOT NULL,
	dia_vencimento int4 NOT NULL,
	limite numeric(15, 2) NOT NULL,
	nome varchar(100) NOT NULL,
	conta_corrente_id int8 NOT NULL,
	usuario_id int8 NOT NULL,
	CONSTRAINT tb_cartao_credito_pkey PRIMARY KEY (id),
	CONSTRAINT fk3x2knrcuqthnd425rbqnia5nd FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id),
	CONSTRAINT fkmiqvni1kqe7ieyg91t6l0p63k FOREIGN KEY (conta_corrente_id) REFERENCES public.tb_conta_corrente(id)
);


-- public.tb_conta definição

-- Drop table

-- DROP TABLE public.tb_conta;

CREATE TABLE public.tb_conta (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	data_vencimento date NOT NULL,
	descricao varchar(255) NOT NULL,
	grupo_parcelamento varchar(255) NULL,
	numero_parcela int4 NOT NULL,
	status varchar(10) NOT NULL,
	tipo varchar(10) NOT NULL,
	total_parcelas int4 NOT NULL,
	valor_original numeric(15, 2) NOT NULL,
	categoria_id int8 NOT NULL,
	parceiro_id int8 NULL,
	usuario_id int8 NOT NULL,
	acrescimo numeric(15, 2) NULL,
	desconto numeric(15, 2) NULL,
	numero_documento varchar(255) NULL,
	CONSTRAINT tb_conta_pkey PRIMARY KEY (id),
	CONSTRAINT tb_conta_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'ATRASADO'::character varying, 'PAGO'::character varying, 'RECEBIDO'::character varying])::text[]))),
	CONSTRAINT tb_conta_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PAGAR'::character varying, 'RECEBER'::character varying])::text[]))),
	CONSTRAINT fk9h7osvev2x22brakn0o3eblbw FOREIGN KEY (categoria_id) REFERENCES public.tb_categoria(id),
	CONSTRAINT fkb7x81d7mw2c4yexqrbbsn6tha FOREIGN KEY (parceiro_id) REFERENCES public.tb_parceiro(id),
	CONSTRAINT fke0eplrystos5hicf7mf9uffse FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id)
);


-- public.tb_conta_baixada definição

-- Drop table

-- DROP TABLE public.tb_conta_baixada;

CREATE TABLE public.tb_conta_baixada (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	acrescimo numeric(15, 2) NOT NULL,
	data_pagamento date NOT NULL,
	desconto numeric(15, 2) NOT NULL,
	juros numeric(15, 2) NOT NULL,
	multa numeric(15, 2) NOT NULL,
	valor_final numeric(15, 2) NOT NULL,
	conta_id int8 NOT NULL,
	conta_corrente_id int8 NOT NULL,
	usuario_id int8 NOT NULL,
	CONSTRAINT tb_conta_baixada_pkey PRIMARY KEY (id),
	CONSTRAINT ukbx95g0pxvqemx96wh7l3s3j01 UNIQUE (conta_id),
	CONSTRAINT fk187pmcu5j8fx8nt1cdrdjk6r0 FOREIGN KEY (conta_corrente_id) REFERENCES public.tb_conta_corrente(id),
	CONSTRAINT fkesyidfsslbo61d7d779u1rut7 FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id),
	CONSTRAINT fkrt5i1blvqs3jrk082qfcs6823 FOREIGN KEY (conta_id) REFERENCES public.tb_conta(id)
);


-- public.tb_lancamento_cartao definição

-- Drop table

-- DROP TABLE public.tb_lancamento_cartao;

CREATE TABLE public.tb_lancamento_cartao (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(100) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(100) NULL,
	last_modified_date timestamp(6) NULL,
	ano_fatura int4 NOT NULL,
	data_compra date NOT NULL,
	descricao varchar(255) NOT NULL,
	grupo_parcelamento varchar(255) NULL,
	mes_fatura int4 NOT NULL,
	numero_parcela int4 NOT NULL,
	total_parcelas int4 NOT NULL,
	valor numeric(15, 2) NOT NULL,
	cartao_credito_id int8 NOT NULL,
	categoria_id int8 NOT NULL,
	usuario_id int8 NOT NULL,
	CONSTRAINT tb_lancamento_cartao_pkey PRIMARY KEY (id),
	CONSTRAINT fkjd2865fv9xm6t9qon1ethwbiq FOREIGN KEY (categoria_id) REFERENCES public.tb_categoria(id),
	CONSTRAINT fkp1cmuje998by066b7dk881h8l FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario(id),
	CONSTRAINT fkrubo2ll27jcqp698qk3ya79xb FOREIGN KEY (cartao_credito_id) REFERENCES public.tb_cartao_credito(id)
);